version: 0.2

phases:
  pre_build:
    commands:
      - echo "Exportando variables de entorno..."
      - export SPRING_DATASOURCE_URL=$DB_URL
      - export SPRING_DATASOURCE_USERNAME=$DB_USER
      - export SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD
      - export SPRING_S3_ACCESS_KEY=$SPRING_S3_ACCESS_KEY
      - export SPRING_S3_SECRET_KEY=$SPRING_S3_SECRET_KEY
      - export SPRING_S3_BUCKET_NAME=$SPRING_S3_BUCKET_NAME

  build:
    commands:
      - echo "Iniciando compilación..."
      - mvn clean package -DskipTests

artifacts:
  files:
    - target/ProjectAPP.jar
  discard-paths: yes
